### ISSUE TITLE
Qual a diferença?

### ISSUE THREAD

**Issue by lucascolette** [rodrigopedra/clearsale-id#1]
Opa, beleza?

Qual a diferença da modalidade ClearSale ID em relação a modalidade utilizada na lib https://github.com/lucasmro/ClearSale/tree/master/docs ?

**Comment by rodrigopedra** [comment]
Fiz este refactor para utilizar num projeto que integrava com a versão 9.6 do manual da ClearSale. Este pacote ainda está em produção e é utilizado diariamente com cerca de 10 mil consultas dentro de um mês.

Sei que mudaram alguns endpoints, por exemplo algumas coisas na nova versão você precisa consultar o endpoint `ExtendedService` que não estava previsto nos manuais anteriores..

Se você olhar individualmente nas entidades verá que o nome das tags XML estão em português no meu pacote, enquanto que no outro estão em inglês. Para a integração com o cliente do referido projeto os endpoints não estavam aceitando as tags XML em inglês conforme o manual versão 9.6.

Além disso fiz alguns poucos refactors na organização das classes. Houve algumas mudanças na estrutura das entidades, pelo novo manual, como por exemplo na entidade Endereco (antigo Address) não há mais o campo "Reference" que na outra implementação estava previsto.

O projeto que comissionou este desenvolvimento utiliza Laravel, se for o mesmo caso que o seu olhe também o pacote: https://github.com/rodrigopedra/laravel-clearsale-id . Não está documentado, mas basicamente toda a manipulação da API é feita através de um serviço e a configuração dos parâmetros é feita num arquivo de config.

**Comment by lucascolette** [comment]
Legal @rodrigopedra . Obrigado pelo esclarecimento.

Abraços!
